server:
  address: 0.0.0.0
  port: 80

spring:
  application:
    name: Sign In Server
  datasource:
    url: jdbc:mysql://localhost:3306/signin_db
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

springdoc:
  swagger-ui:
    enabled: true
    displayRequestDuration: true
  api-docs:
    enabled: true
  packages-to-scan: cn.edu.dlut.mail.wuchen2020.signinserver.controller
